services:
  pluralflux:
    image: pluralflux
    build:
      context: .
      dockerfile: Dockerfile
  postgres:
    image: postgres:latest
    container_name: pluralflux-postgres
    environment:
      POSTGRES_PASSWORD: /run/secrets/postgres_pwd
    secrets:
      - postgres_pwd
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    environment:
      # Required by pgAdmin
      PGADMIN_DEFAULT_EMAIL: pieartsy@pm.me
      PGADMIN_DEFAULT_PASSWORD: /run/secrets/postgres_pwd
      # Don't require the user to login
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      # Don't require a "master" password after logging in
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    secrets:
      - postgres_pwd

volumes:
  pgdata:

secrets:
  postgres_pwd:
    file: ./postgres_pwd.txt