services:
  main:
    build: .
    container_name: pluralflux
  postgres:
    image: postgres:latest
    container_name: pluralflux-postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pwd
    secrets:
      - postgres_pwd
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
#  pgadmin:
#    image: dpage/pgadmin4:latest
#    ports:
#      - 5050:80
#    environment:
#      # Required by pgAdmin
#      PGADMIN_DEFAULT_EMAIL: pieartsy@pm.me
#      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/postgres_pwd
#      # Don't require the user to login
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#      # Don't require a "master" password after logging in
#      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
#    secrets:
#      - postgres_pwd

volumes:
  pgdata:

secrets:
  postgres_pwd:
    file: ./secrets/postgres-password.txt
